Makefile is a special file used in software development projects, particularly those written in C, C++, and similar languages. It contains rules and dependencies that specify how to compile and build the project. Makefiles are processed by a utility called make, which automatically determines which parts of the project need to be recompiled and issues the necessary commands to rebuild them.

Here are some key components and concepts related to Makefiles:

Targets: Each rule in a Makefile typically defines a target, which is the file or task that needs to be built. Targets can include executable programs, object files, libraries, documentation, etc.

Dependencies: Rules also specify dependencies, which are the files or tasks that the target depends on. If any of the dependencies are newer than the target, the target needs to be rebuilt.

Commands: For each target, the Makefile includes a set of commands that make will execute to build the target. These commands are typically shell commands (e.g., gcc commands to compile source files).

Variables: Makefiles can define variables to store values that are used throughout the file. Variables can be used to specify compiler options, file names, directories, etc. This makes it easier to customize the build process and maintain consistency.

Patterns and wildcards: Makefiles can use patterns and wildcards to specify rules that apply to multiple targets or dependencies. This allows for more concise and flexible Makefile syntax.

Makefiles are particularly useful for managing large projects with many source files, where manually compiling each file and managing dependencies would be impractical. By automating the build process, Makefiles help ensure that only the necessary parts of the project are rebuilt when changes are made, saving time and improving productivity for developers.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Having multiple target in one rule is the same as setting each of those targets with the same commands
Example:
~~~~~~~~~~~~~~~~
all: f1.0 f2.0

f1.0 f2.0:
	echo ${@}

is exactly the same as

f1.0:
	echo ${@}
f2.0:
	echo ${@}
~~~~~~~~~~~~~~~~
If we set dependencies of all to f1.0 only
~~~~~~~~~~~~~~~~
all: f1.0

f1.0 f2.0:
    echo $@
~~~~~~~~~~~~~~~~
This will only execute f1.0. Here, "$@" is an automatic variable. The "@" specify the target. There is another automatic variable that specify all newer prerequisite than target which is "$?". The "?" is not a wildcard character in this case. Below is a list of commonly used automatic variable:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$@: Represents the target filename.
$<: Represents the first prerequisite filename.
$^: Represents the list of all prerequisites (without duplicates).
$?: Represents the list of prerequisites that are newer than the target.
$: Represents the stem of the filename (the part that matches the pattern in a pattern rule).
$%: Represents the target member name in an archive file.
$*: Represents the stem of the filename (like $, but does not include the suffix).
$(@D): Represents the directory part of the target filename.
$(@F): Represents the file part of the target filename.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
clean is not a special makefile keyword and so is all

wildcards has it's own function. It's best to use when assigning patterns to variable
Look at example below
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
files := $(wildcard *.c) != files := *.c
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In lhs, variable files will be assigned with all files matching the patern. In rhs, variable files will be assigned as *.c
Basically, the wildcard function returns the list of specified pattern